// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version   string             `json:"version"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type UserAccount struct {
	ID                uuid.UUID          `json:"id"`
	Plan              string             `json:"plan"`
	PlanStartedAt     time.Time          `json:"plan_started_at"`
	PlanEndsAt        pgtype.Timestamptz `json:"plan_ends_at"`
	BillingCustomerID *string            `json:"billing_customer_id"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}
