// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetUserAccount(ctx context.Context, id uuid.UUID) (*UserAccount, error)
}

var _ Querier = (*Queries)(nil)
