// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const GetUserAccount = `-- name: GetUserAccount :one
SELECT id, plan, plan_started_at, plan_ends_at, billing_customer_id, created_at, updated_at FROM public.user_accounts
WHERE id = $1
`

func (q *Queries) GetUserAccount(ctx context.Context, id uuid.UUID) (*UserAccount, error) {
	row := q.db.QueryRow(ctx, GetUserAccount, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Plan,
		&i.PlanStartedAt,
		&i.PlanEndsAt,
		&i.BillingCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
